added content for building attendance using sessions API
100mslive/100ms-docs pull request #1089
Opened 2023-01-09 03:50 UTC by Nixon-Samuel

2023-01-13 05:00 UTC, arjunattam requested changes

2023-01-13 10:44 UTC, Nixon-Samuel commented on docs/server-side/v2/Sessions/example-build-attendance.mdx
> +You can use `Retrieve a session API` to get the individual participants' duration, total session duration, and aggregated participants' duration. And use the data export option from the 100ms dashboa
added

2023-01-13 10:44 UTC, Nixon-Samuel commented on docs/server-side/v2/Sessions/example-build-attendance.mdx
> +-   Listen to the `session.close.success` webhook event, which indicates that the particular session has ended.
added

2023-01-13 10:44 UTC, Nixon-Samuel commented on docs/server-side/v2/Sessions/example-build-attendance.mdx
> +You can use `Retrieve a session API` to get the individual participants' duration, total session duration, and aggregated participants' duration. And use the data export option from the 100ms dashboa
fixed it.

2023-01-17 04:48 UTC, arjunattam approved these changes

2023-01-17 04:48 UTC, merged