change markdown compiler from next-mdx-remote to mdx-bundler
100mslive/100ms-docs pull request #1126
Opened 2023-01-13 06:03 UTC by mackarelfish

2023-01-17 03:10 UTC, saikatmitra91 commented
@mackarelfish  can we fix linters and resolve conflicts ?

2023-01-17 04:19 UTC, mackarelfish commented
> @mackarelfish can we fix linters and resolve conflicts ?

looking into the vale linter today

2023-01-19 04:29 UTC, saikatmitra91 requested changes

2023-01-25 07:15 UTC, mackarelfish commented on lib/image.js
> +        visit(tree, 'image', (node, index, parent) => {
the docs images should already been prefixed by /docs

2023-01-25 10:13 UTC, saikatmitra91 approved these changes

2023-01-25 10:53 UTC, merged