feat: add doc for hls timed metadata
100mslive/100ms-docs pull request #1235
Opened 2023-02-03 02:49 UTC by amar-1995

2023-02-03 04:43 UTC, raviteja83 commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +    "start_date": "UTC date", // The time when the event is received. Duplicate of START-DATE
what is START-DATE? is it obvious for someone reading the docs?

2023-02-03 04:45 UTC, raviteja83 commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +>Please Note : Above implementation will be changed after we introducted HLS controller library.
Note: Above implementation might change in future.

2023-02-03 04:45 UTC, raviteja83 commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +## Limitions
Limitations. @Nixon-Samuel vale did not find this typo.

2023-02-03 04:47 UTC, raviteja83 commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +## Requirements
Let's also add minimum supported version here.

2023-02-03 09:56 UTC, raviteja83 commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +-   hms-video-web min version: 0.4.0
let us hms-video-store or react-sdk. both of them need not be there.

2023-02-06 07:06 UTC, Nixon-Samuel requested changes

2023-02-06 07:06 UTC, Nixon-Samuel commented on .github/styles/Vocab/HMSVocab/accept.txt
> +ffmpeg
shall we update the actual conent to "FFmpeg"

2023-02-06 07:06 UTC, Nixon-Samuel commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +- It’s hard to sync metadata with stream exactly due to the latency from ffmpeg creating the stream. To address this, we’ve added 2s the actual `START-DATE` attribute.
please fix this vale error.

2023-02-06 07:09 UTC, Nixon-Samuel commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +    "payload": "payload sent by the user",
shall we update this with an actual example and add comments for relevance?

2023-02-06 07:10 UTC, Nixon-Samuel commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +### APP side implementation
update this to App instead of APP

2023-02-06 07:10 UTC, Nixon-Samuel commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +>Please Note : Above implementation might change in future.
Can be just "Note" instead of "Please Note"

2023-02-06 07:11 UTC, Nixon-Samuel commented on docs/javascript/v2/how--to-guides/record-and-live-stream/hls/hls-timed-metadata.mdx
> +- It’s hard to sync metadata with stream exactly due to the latency from ffmpeg creating the stream. To address this, we’ve added 2s the actual `START-DATE` attribute.
This is unclear - "To address this, we’ve added 2s the actual `START-DATE` attribute."

2023-02-06 07:33 UTC, Nixon-Samuel approved these changes

2023-02-06 08:29 UTC, merged