added API to allow switching Audio Output device on iOS
100mslive/100ms-docs pull request #1615
Opened 2023-06-19 18:23 UTC by stanwolverine

2023-06-20 04:40 UTC, ygit requested changes
@stanwolverine Add an image of the iOS UI

2023-06-20 04:40 UTC, ygit commented on docs/react-native/v2/how-to-guides/configure-your-device/speaker/audio-output-routing.mdx
> +### Switch Audio Output Device using iOS AirPlay UI
Add an image of the iOS UI

2023-06-20 06:54 UTC, stanwolverine commented on docs/react-native/v2/how-to-guides/configure-your-device/speaker/audio-output-routing.mdx
> +### Switch Audio Output Device using iOS AirPlay UI
Now it's working

2023-06-21 07:11 UTC, ygit approved these changes

2023-06-21 07:11 UTC, merged