Remove references to noise suppression
100mslive/100ms-docs pull request #1645
Opened 2023-07-04 06:10 UTC by KaustubhKumar05

2023-07-04 06:14 UTC, saikatmitra91 requested changes

2023-07-04 06:14 UTC, saikatmitra91 commented on docs/javascript/v2/how-to-guides/extend-capabilities/plugins/noise-suppression.mdx
we should mark this as deprecated rather removing it fully.

2023-07-04 06:51 UTC, KaustubhKumar05 commented on docs/javascript/v2/how-to-guides/extend-capabilities/plugins/noise-suppression.mdx
Updated, please re-review

2023-07-06 06:22 UTC, saikatmitra91 approved these changes

2023-07-06 06:23 UTC, merged