Updated polls permission
100mslive/100ms-docs pull request #1669
Opened 2023-07-20 05:14 UTC by amit1-100ms

2023-07-20 07:28 UTC, arjunattam approved these changes

2023-07-21 10:44 UTC, saikatmitra91 requested changes

2023-07-21 10:44 UTC, saikatmitra91 commented on docs/server-side/v2/api-reference/policy/create-template-via-api.mdx
> +| pollWrite    | `boolean` | Permission whether poll/quiz information can be modified  | No       | `false` |
@amit-100ms  please mention pollwrite implicitly means one has read permission

2023-07-24 10:07 UTC, saikatmitra91 approved these changes

2023-07-25 06:26 UTC, merged