hide beam Update release-notes.mdx
100mslive/100ms-docs pull request #1722
Opened 2023-08-11 07:34 UTC by mntrspace

2023-08-11 10:09 UTC, chdinesh1089 commented
resolved the conflict. Can we merge this? Looks good to me. @mntrspace @arjunattam

2023-08-11 10:13 UTC, chdinesh1089 approved these changes

2023-08-17 05:08 UTC, raviteja83 approved these changes

2023-08-17 05:35 UTC, saikatmitra91 requested changes

2023-08-17 05:35 UTC, saikatmitra91 commented on docs/javascript/v2/changelog/release-notes.mdx
> +Starting from version `0.10.12` of `@100mslive/hms-video-store`:
should we mention react-sdk version too ?

2023-08-24 02:53 UTC, mntrspace reviewed
Added react-sdk version

2023-08-24 03:57 UTC, KaustubhKumar05 approved these changes

2023-08-24 04:15 UTC, merged