docs: add release notes
100mslive/100ms-docs pull request #1778
Opened 2023-09-22 13:28 UTC by raviteja83

2023-09-26 04:50 UTC, saikatmitra91 requested changes

2023-09-26 04:50 UTC, saikatmitra91 commented on docs/javascript/v2/how-to-guides/build-interactive-features/handraise.mdx
> +    constisHandRaised  = peer.isHandRaised;
```suggestion
    const isHandRaised  = peer.isHandRaised;
```

2023-09-26 04:50 UTC, saikatmitra91 commented on docs/javascript/v2/how-to-guides/build-interactive-features/handraise.mdx
> +    const peer = notification.data;
```suggestion
    const { peer } = notification.data;
```
isnt the data of above format ?

2023-09-27 05:32 UTC, raviteja83 commented on docs/javascript/v2/how-to-guides/build-interactive-features/handraise.mdx
> +    const peer = notification.data;
nope data itself is hmsPeer.

2023-09-27 05:34 UTC, saikatmitra91 approved these changes

2023-09-28 09:40 UTC, merged