feat: create a section for large room
100mslive/100ms-docs pull request #1802
Opened 2023-10-10 12:14 UTC by raviteja83

2023-10-11 12:56 UTC, saikatmitra91 requested changes

2023-10-11 12:56 UTC, saikatmitra91 commented on docs/javascript/v2/how-to-guides/large-room/handling-peerlist.mdx
handling-large-room

2024-02-16 05:14 UTC, KaustubhKumar05 commented
Can this PR be closed @raviteja83?

2024-03-04 09:31 UTC, KaustubhKumar05 commented
Title change included in https://github.com/100mslive/100ms-docs/pull/2052

2024-03-04 09:31 UTC, closed without merging