fix: broken links in js docs
100mslive/100ms-docs pull request #627
Opened 2022-06-28 12:02 UTC by eswarclynn

2022-06-28 12:30 UTC, saikatmitra91 requested changes

2022-06-28 12:30 UTC, saikatmitra91 commented on components/Header.tsx
> +                        <Link href={`/${getCurrentTech() || 'javascript'}/`}> Docs</Link>
why calling `getCurrentTech()` again ? 

can we reuse `currentTech` ?

2022-06-28 12:30 UTC, saikatmitra91 commented on components/Header.tsx
> +        const currentTech = getCurrentTech() || 'javascript';
shouldnt this logic be inside `getCurrentTech` function ? 🤔

2022-06-29 02:34 UTC, saikatmitra91 commented
@eswarclynn can we also check if this page is needed or not 

https://www.100ms.live/docs/v2/client-sdks/Getting-Started-Javascript

2022-06-29 06:01 UTC, eswarclynn commented
> @eswarclynn can we also check if this page is needed or not
> 
> https://www.100ms.live/docs/v2/client-sdks/Getting-Started-Javascript

No we're not, checked with the team too. Do you want it removed?

2022-07-08 10:26 UTC, saikatmitra91 approved these changes

2022-07-08 10:26 UTC, merged