GG-54: steps-container styles, add steps-container to javascript quick…
100mslive/100ms-docs pull request #999
Opened 2022-12-21 10:43 UTC by mackarelfish

added steps ui

2022-12-23 04:07 UTC, saikatmitra91 commented
<img width="351" alt="Screenshot 2022-12-23 at 9 36 50 AM" src="https://user-images.githubusercontent.com/10416686/209268975-17708d13-d787-47ad-99a3-11b4e44577da.png">

the alignment is off @mackarelfish

2022-12-23 04:10 UTC, saikatmitra91 requested changes

2022-12-23 04:10 UTC, saikatmitra91 commented on styles/theme.css
> +  background: #f3f3f3;
why not use css variables here ?

2022-12-23 04:10 UTC, saikatmitra91 commented on styles/theme.css
> +  border-color: rgb(229 231 235/1);
css variable ?

2022-12-26 05:32 UTC, mackarelfish commented
@saikatmitra91 should be resolved by now

2022-12-28 02:30 UTC, saikatmitra91 approved these changes

2022-12-28 02:31 UTC, merged